### ISSUE TITLE
Is this ready to be added to the FreeCAD-addons repo?

### ISSUE THREAD

**Issue by luzpaz** [oddtopus/dodo#1]

**Comment by oddtopus** [comment]
Yes. It's stable under FreeCad 0.18 and 0.19 using Python 3.6 and Qt5

**Comment by luzpaz** [comment]
Added to FreeCAD-addons in https://github.com/FreeCAD/FreeCAD-addons/commit/ba884403645706d7d77e7a1a374c19c8896dbbad 
:+1:
