### ISSUE TITLE
'FeaturePython' object has no attribute 'spin'

### ISSUE THREAD

**Issue by trostn** [oddtopus/dodo#16]
Hi, 

whenever I try to use the FrameBranch Manager to get some frames even around the simplest cube FreeCAD prints the following error message. Sometimes the frames are still drawn correctly, sometimes pretty weirdly.
Can anybody help on that? maybe it's an OSI layer 8 problem? ;-)

21:58:51  Traceback (most recent call last):
  File "C:\Users\<User>\AppData\Roaming\FreeCAD\Mod\dodo\fFeatures.py", line 684, in execute
    beam.AttachmentOffset.Rotation=FreeCAD.Rotation(Z,angle+beam.spin)
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'spin'

**Comment by saiinformatica** [comment]
I've had the same problem, fixed by adding the line:
`beam.addProperty("App::PropertyFloat","spin","FrameBranch","The rotation of the section")`
to fFeatures.py on line 696.
Seems it has been removed by accident on commit 27b1e95

**Comment by trostn** [comment]
The solution came from saiinformatica:

Adding the line:
beam.addProperty("App::PropertyFloat","spin","FrameBranch","The rotation of the section")
to fFeatures.py on line 696.
Seems it has been removed by accident on commit [27b1e95](https://github.com/oddtopus/dodo/commit/27b1e95ae341b52d4132127a376eeb49a0d896ae)
